### ISSUE TITLE
Published Paper?

### ISSUE THREAD

**Issue by marketneutral** [sdv-dev/DeepEcho#59]
Hi- is there a paper on the PAR model available? Thank you.

**Comment by bfernandezcastro** [comment]
Hi

if not a paper, a deeper technical description of  PAR algorithm will be extremely useful. 

Thanks.

**Comment by npatki** [comment]
Hello! A preprint of the paper is available here: https://arxiv.org/pdf/2207.14406.pdf

Marking the issue as closed since it's an older one. Please feel free to reply if there are any follow ups.
